import './globals.css'
import { Merriweather_Sans, Roboto_Mono } from 'next/font/google'

const sans = Merriweather_Sans({ subsets: ['latin'], variable: '--font-sans' })
const mono = Roboto_Mono({ subsets: ['latin'], variable: '--font-mono' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sans.className} ${sans.variable} ${mono.variable}`}>{children}</body>
    </html>
  )
}
